openapi: 3.0.3
info:
  title: Go-chat
  description: Chat in Golang
  version: 1.0.0
servers:
  - url: http://localhost:8080/

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        userName:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - name
        - userName
        - password

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message


paths:
  /users:
    post:
      summary: Creates a new user
      description: Creates a new user
      operationId: addUser
      requestBody:
        description: Add user to chat
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{id}:
    get:
      summary: Returns a user by ID
      description: Returns a use based on a single ID
      operationId: findUserByID
      parameters:
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'